import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    // <>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=deviceWidth, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <main>
    //     <aside classNameName={`${styles.sidebar} ${styles.dataSidebar}`}>
    //       <div className="sidebarInfo">
    //         <figure classNameName="avatarBox">
    //           <img
    //             src="./assets/images/aayush-avatar.png"
    //             alt="Aayush Mehta"
    //             width="80"
    //           />
    //         </figure>

    //         <div className="infoContent">
    //           <h1 className="name" title="Richard hanrick">
    //             Aayush Mehta
    //           </h1>

    //           <p className="title">Web developer</p>
    //         </div>

    //         <button className="info_moreBtn" dataSidebarBtn>
    //           <span>Show Contacts </span>

    //           <ionIcon name="chevronDown"></ionIcon>
    //         </button>
    //       </div>

    //       <div className="sidebarInfoMore">
    //         <div className="separator"></div>

    //         <ul className="contactsList">
    //           <li className="contactItem">
    //             <div className="iconBox">
    //               <ionIcon name="mailOutline"></ionIcon>
    //             </div>

    //             <div className="contactInfo">
    //               <p className="contactTitle">Email</p>

    //               <a href="mailto:hi@aayushmehta.com" className="contactLink">
    //                 hi@aayushmehta.com
    //               </a>
    //             </div>
    //           </li>

    //           <li className="contactItem">
    //             <div className="iconBox">
    //               <ionIcon name="calendarOutline"></ionIcon>
    //             </div>

    //             <div className="contactInfo">
    //               <p className="contactTitle">Birthday</p>

    //               <time datetime="1982-06-23">Febuary 28, 2001</time>
    //             </div>
    //           </li>

    //           <li className="contactItem">
    //             <div className="iconBox">
    //               <ionIcon name="locationOutline"></ionIcon>
    //             </div>

    //             <div className="contactInfo">
    //               <p className="contactTitle">Location</p>

    //               <address>Bengaluru, India</address>
    //             </div>
    //           </li>
    //         </ul>

    //         <div className="separator"></div>

    //         <ul className="socialList">
    //           <li className="socialItem">
    //             <a
    //               href="https://www.linkedin.com/in/aayush-mehta-2b7028147/"
    //               className="socialLink"
    //               target="_blank"
    //             >
    //               <ionIcon name="logoLinkedin"></ionIcon>
    //             </a>
    //           </li>
    //           <li className="socialItem">
    //             <a
    //               href="https://github.com/AayushMehta"
    //               className="socialLink"
    //               target="_blank"
    //             >
    //               <ionIcon name="logo-github"></ionIcon>
    //             </a>
    //           </li>
    //           <li className="socialItem">
    //             <a
    //               href="https://medium.com/@aayushmehta5225"
    //               className="socialLink"
    //               target="_blank"
    //             >
    //               <ionIcon name="logo-medium"></ionIcon>
    //             </a>
    //           </li>
    //           <li className="socialItem">
    //             <a
    //               href="mailto:hi@aayushmehta.com"
    //               className="socialLink"
    //               target="_blank"
    //             >
    //               <ionIcon name="mail-outline"></ionIcon>
    //             </a>
    //           </li>
    //         </ul>
    //       </div>
    //     </aside>

    //     <div className="mainContent">
    //       <nav className="navbar">
    //         <ul className="navbarList">
    //           <li className="navbarItem">
    //             <button className="navbarLink active" data-navLink>
    //               About
    //             </button>
    //           </li>

    //           <li className="navbarItem">
    //             <button className="navbarLink" data-navLink>
    //               Resume
    //             </button>
    //           </li>

    //           <li className="navbarItem">
    //             <button className="navbarLink" data-navLink>
    //               Portfolio
    //             </button>
    //             add _modified to data-nav-link to disable button
    //           </li>

    //           <li className="navbarItem">
    //             <button className="navbarLink" data-navLink>
    //               Blog
    //             </button>
    //           </li>
    //         </ul>
    //       </nav>

    //       <article className="about active" data-page="about">
    //         <header>
    //           <h2 className="h2 articleTitle">About me</h2>
    //         </header>

    //         <section className="aboutText">
    //           <p>
    //             I'm Frontend developer from Bengaluru, india, working on
    //             Freelance Projects. I enjoy turning complex problems into
    //             simple, beautiful and intuitive designs.
    //           </p>

    //           <p>
    //             My job is to build your website so that it is functional and
    //             user-friendly but at the same time attractive. Moreover, I add
    //             personal touch to your product and make sure that is eyeCatching
    //             and easy to use. My aim is to bring across your message and
    //             identity in the most creative way.
    //           </p>
    //         </section>

    //         <section className="service">
    //           <h3 className="h3 serviceTitle">What i'm doing</h3>

    //           <ul className="serviceList">
    //             <li className="serviceItem">
    //               <div className="serviceIconBox">
    //                 <img
    //                   src="./assets/images/icon-dev.svg"
    //                   alt="Web development icon"
    //                   width="40"
    //                 />
    //               </div>

    //               <div className="serviceContentBox">
    //                 <h4 className="h4 serviceItemTitle">Web development</h4>

    //                 <p className="serviceItemText">
    //                   High-quality development of sites at the professional
    //                   level.
    //                 </p>
    //               </div>
    //             </li>

    //             <li className="serviceItem">
    //               <div className="serviceIconBox">
    //                 {/* <img
    //                 src="./assets/images/icon-design.svg
    //             "
    //                 alt="design icon"
    //                 width="40"
    //               /> */}
    //               </div>

    //               <div className="serviceContentBox">
    //                 <h4 className="h4 serviceItemTitle">Web Design</h4>

    //                 <p className="serviceItemText">
    //                   The most modern and high-quality design made at a
    //                   professional leve
    //                 </p>
    //               </div>
    //             </li>

    //             <li className="serviceItem">
    //               <div className="serviceIconBox">
    //                 {/* <!-- <img
    //                 src="./assets/images/icon-app.svg"
    //                 alt="mobile app icon"
    //                 width="40"
    //               /> --> */}
    //               </div>

    //               <div className="serviceContentBox">
    //                 <h4 className="h4 serviceItemTitle">Mobile apps</h4>

    //                 <p className="serviceItemText">
    //                   Professional development of applications for iOS and
    //                   Android.
    //                 </p>
    //               </div>
    //             </li>

    //             <li className="serviceItem">
    //               <div className="serviceIconBox">
    //                 {/* <!-- <img
    //                 src="./assets/images/icon-photo.svg"
    //                 alt="camera icon"
    //                 width="40"
    //               /> --> */}
    //               </div>

    //               <div className="serviceContentBox">
    //                 <h4 className="h4 serviceItemTitle">Photography</h4>

    //                 <p className="serviceItemText">
    //                   I make high-quality photos of any category at a
    //                   professional level.
    //                 </p>
    //               </div>
    //             </li>
    //           </ul>
    //         </section>
    //       </article>

    //       <article className="resume" data-page="resume">
    //         <header>
    //           <h2 className="h2 articleTitle">Resume</h2>
    //         </header>

    //         <section className="timeline">
    //           <div className="titlerapper">
    //             <div className="iconBox">
    //               <ionIcon name="book-outline"></ionIcon>
    //             </div>

    //             <h3 className="h3">Education</h3>
    //           </div>

    //           <ol className="timelineList">
    //             <li className="timelineItem">
    //               <h4 className="h4 timelineItemTitle">
    //                 JK Lakshmipat Univeraity
    //               </h4>

    //               <span>2019 — 2023</span>

    //               <p className="timelineText">B.Tech Computer Science</p>
    //             </li>
    //           </ol>
    //         </section>

    //         <section className="timeline">
    //           <div className="titleWrapper">
    //             <div className="iconBox">
    //               <ionIcon name="book-outline"></ionIcon>
    //             </div>

    //             <h3 className="h3">Experience</h3>
    //           </div>

    //           <ol className="timelineList">
    //             {/* <li className="timelineItem">
    //             <h4 className="h4 timelineItemTitle">CTO</h4>

    //             <h5>BrickByBit</h5>
    //             <span>June, 2023 - Present</span>

    //             <p className="timelineText">Web Developmnent Company</p>
    //           </li>  */}
    //             <li className="timelineItem">
    //               <h4 className="h4 timelineItemTitle">Frontend Developer</h4>

    //               <h5>Doorpix</h5>
    //               <span>Jan, 2023 - Present</span>

    //               <p className="timelineText">
    //                 Develop web applications based on HTML , CSS , JS , React JS
    //               </p>
    //             </li>
    //             <li className="timelineItem">
    //               <h4 className="h4 timelineItemTitle">
    //                 Information Security Analyst Intern
    //               </h4>
    //               <h5>Cronytechnovest</h5>
    //               <span>July, 2021 — September, 2021 (3 months)</span>

    //               <p className="timelineText">
    //                 Vulnerability Assessment and Penetration Testing(VAPT){" "}
    //                 <br />
    //                 Network penetration testing <br />
    //                 Mobile penetration testing
    //                 <br />
    //               </p>
    //             </li>
    //           </ol>
    //         </section>
    //       </article>

    //       <article className="portfolio" data-page="portfolio">
    //         <headata-filteder>
    //           <h2 className="h2 articleTitle">Portfolio</h2>
    //         </headata-filteder>

    //         <section className="projects">
    //           <div className="filterSelectBox">
    //             <button className="filterSelect" dataSelect></button>
    //           </div>
    //           <div className="projectList">
    //             <a href="https://discover-jodhpur.netlify.app" target="_blank">
    //               <div className="projectCover">
    //                 <img
    //                   src="./assets/images/discover-jodhpurCover.png"
    //                   alt="discover-jodhpur"
    //                   loading="lazy"
    //                 />
    //                 <h4>Discover Jodhpur</h4>
    //               </div>
    //             </a>
    //             <a href="https://excrusion.netlify.app" target="_blank">
    //               <div className="projectCover">
    //                 <img
    //                   src="./assets/images/excrusionCover.png"
    //                   alt="Excrusion"
    //                   loading="lazy"
    //                 />
    //                 <h4>Excrusion</h4>
    //               </div>
    //             </a>
    //             <a href="https://healthy-omni-food.netlify.app" target="_blank">
    //               <div className="projectCover">
    //                 <img
    //                   src="./assets/images/healthy-omni-food.png"
    //                   alt="Omni Food"
    //                   loading="lazy"
    //                 />
    //                 <h4>Omni Food</h4>
    //               </div>
    //             </a>
    //             <a
    //               href="https://yoga-studioWebsite.netlify.app"
    //               target="_blank"
    //             >
    //               <div className="projectCover">
    //                 <img
    //                   src="./assets/images/yoga-studio.png"
    //                   alt="Yoga Studio"
    //                   loading="lazy"
    //                 />
    //                 <h4>Yoga Studio</h4>
    //               </div>
    //             </a>
    //           </div>
    //         </section>
    //       </article>
    //       <article className="blog" data-page="blog">
    //         <header>
    //           <h2 className="h2 articleTitle">Blog</h2>
    //         </header>

    //         <section className="blogPosts">
    //           <ul className="blogPostsList">
    //             <li className="blogPostItem">
    //               <a
    //                 href="https://medium.com/@aayushmehta5225/howTo-become-productive-as-a-developer-2a4b2c3d0758"
    //                 target="_blank"
    //               >
    //                 {/* <figure className="blogBannerBox">
    //                 <img
    //                   src="./assets/images/blog-6.jpg"
    //                   alt="Design digest #79"
    //                   loading="lazy"
    //                 />
    //               </figure>  */}

    //                 <div className="blogContent">
    //                   <div className="blogMeta">
    //                     <p className="blogCategory">Web Development</p>

    //                     <span className="dot"></span>

    //                     <time datetime="2022-02-23">April 05, 2023</time>
    //                   </div>

    //                   <h4 className="h4 blogItemTitle">
    //                     How to become productive as a developer
    //                   </h4>

    //                   {/* <!-- <p className="blogText">
    //                   How to become productive as a developer
    //                 </p> --> */}
    //                 </div>
    //               </a>
    //             </li>
    //             <li className="blogPostItem">
    //               <a
    //                 href="https://medium.com/@aayushmehta5225/understanding-box-sizing-and-border-box-2407b8415e06"
    //                 target="_blank"
    //               >
    //                 {/* <!-- <figure className="blog-banner-box">
    //               <img src="#" alt="#" loading="lazy" />
    //               </figure> --> */}

    //                 <div className="blogContent">
    //                   <div className="blogMeta">
    //                     <p className="blogCategory">Web Development</p>

    //                     <span className="dot"></span>

    //                     <time datetime="2022-02-23">April 10, 2023</time>
    //                   </div>

    //                   <h4 className="h4 blogItemTitle">
    //                     Understanding box-Sizing and border-box
    //                   </h4>

    //                   {/* <!-- <p className="blogText">
    //                   Understanding box-Sizing and border-box
    //                 </p> --> */}
    //                 </div>
    //               </a>
    //             </li>
    //             <li className="blogPostItem">
    //               <a
    //                 href="https://medium.com/@aayushmehta5225/gridTemplate-area-6a7b9ec94e8a"
    //                 target="_blank"
    //               >
    //                 {/* <!-- <figure className="blog-banner-box">
    //                 <img src="#" alt="#" loading="lazy" />
    //               </figure> --> */}

    //                 <div className="blogContent">
    //                   <div className="blogMeta">
    //                     <p className="blogCategory">Web Development</p>

    //                     <span className="dot"></span>

    //                     <time datetime="2022-02-23">April 11, 2023</time>
    //                   </div>

    //                   <h4 className="h4 blogItemTitle">
    //                     Understanding gridTemplate area
    //                   </h4>

    //                   {/* <!-- <p className="blogText">
    //                   Understanding box-Sizing and border-box
    //                 </p> --> */}
    //                 </div>
    //               </a>
    //             </li>
    //           </ul>
    //         </section>
    //       </article>
    //     </div>
    //   </main>
    // </>
    <>
      <meta charSet="UTF-8" />
      <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      {/* Google tag (gtag.js) */}
      <title>Aayush Mehta</title>
      {/*
    - favicon
  */}
      <link
        rel="shortcut icon"
        href="./assets/images/logo-A - Edited.png"
        type="image/x-icon"
      />
      {/*
    - custom css link
  */}
      <link rel="stylesheet" href="./assets/css/style.css" />
      {/*
    - google font link
  */}
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
      <link
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap"
        rel="stylesheet"
      />
      <main>
        <aside className="sidebar" data-sidebar="">
          <div className="sidebar-info">
            <figure className="avatar-box">
              <img
                src="./assets/images/aayush-avatar.png"
                alt="Aayush Mehta"
                width={80}
              />
            </figure>
            <div className="info-content">
              <h1 className="name" title="Richard hanrick">
                Aayush Mehta
              </h1>
              <p className="title">Web developer</p>
            </div>
            <button className="info_more-btn" data-sidebar-btn="">
              <span>Show Contacts </span>
              <ion-icon name="chevron-down" />
            </button>
          </div>
          <div className="sidebar-info_more">
            <div className="separator" />
            <ul className="contacts-list">
              <li className="contact-item">
                <div className="icon-box">
                  <ion-icon name="mail-outline" />
                </div>
                <div className="contact-info">
                  <p className="contact-title">Email</p>
                  <a href="mailto:hi@aayushmehta.com" className="contact-link">
                    hi@aayushmehta.com
                  </a>
                </div>
              </li>
              <li className="contact-item">
                <div className="icon-box">
                  <ion-icon name="calendar-outline" />
                </div>
                <div className="contact-info">
                  <p className="contact-title">Birthday</p>
                  <time dateTime="1982-06-23">Febuary 28, 2001</time>
                </div>
              </li>
              <li className="contact-item">
                <div className="icon-box">
                  <ion-icon name="location-outline" />
                </div>
                <div className="contact-info">
                  <p className="contact-title">Location</p>
                  <address>Bengaluru, India</address>
                </div>
              </li>
            </ul>
            <div className="separator" />
            <ul className="social-list">
              <li className="social-item">
                <a
                  href="https://www.linkedin.com/in/aayush-mehta-2b7028147/"
                  className="social-link"
                  target="_blank"
                >
                  <ion-icon name="logo-linkedin" />
                </a>
              </li>
              <li className="social-item">
                <a
                  href="https://github.com/AayushMehta"
                  className="social-link"
                  target="_blank"
                >
                  <ion-icon name="logo-github" />
                </a>
              </li>
              <li className="social-item">
                <a
                  href="https://medium.com/@aayushmehta5225"
                  className="social-link"
                  target="_blank"
                >
                  <ion-icon name="logo-medium" />
                </a>
              </li>
              <li className="social-item">
                <a
                  href="mailto:hi@aayushmehta.com"
                  className="social-link"
                  target="_blank"
                >
                  <ion-icon name="mail-outline" />
                </a>
              </li>
            </ul>
          </div>
        </aside>
        <div className="main-content">
          <nav className="navbar">
            <ul className="navbar-list">
              <li className="navbar-item">
                <button className="navbar-link active" data-nav-link="">
                  About
                </button>
              </li>
              <li className="navbar-item">
                <button className="navbar-link" data-nav-link="">
                  Resume
                </button>
              </li>
              {/* PORTFOLIO COMPANY TO BE ACTIVATED LATER */}
              <li className="navbar-item">
                <button className="navbar-link" data-nav-link="">
                  Portfolio
                </button>
                {/* add _modified to data-nav-link to disable button */}
              </li>
              <li className="navbar-item">
                <button className="navbar-link" data-nav-link="">
                  Blog
                </button>
              </li>
            </ul>
          </nav>
          <article className="about active" data-page="about">
            <header>
              <h2 className="h2 article-title">About me</h2>
            </header>
            <section className="about-text">
              <p>
                I'm Frontend developer from Bengaluru, india, working on
                Freelance Projects. I enjoy turning complex problems into
                simple, beautiful and intuitive designs.
              </p>
              <p>
                My job is to build your website so that it is functional and
                user-friendly but at the same time attractive. Moreover, I add
                personal touch to your product and make sure that is
                eye-catching and easy to use. My aim is to bring across your
                message and identity in the most creative way.
              </p>
            </section>
            <section className="service">
              <h3 className="h3 service-title">What i'm doing</h3>
              <ul className="service-list">
                <li className="service-item">
                  <div className="service-icon-box">
                    {/* <img
              src="./assets/images/icon-dev.svg"
              alt="Web development icon"
              width="40"
            /> */}
                  </div>
                  <div className="service-content-box">
                    <h4 className="h4 service-item-title">Web development</h4>
                    <p className="service-item-text">
                      High-quality development of sites at the professional
                      level.
                    </p>
                  </div>
                </li>
                <li className="service-item">
                  <div className="service-icon-box">
                    {/* <img
              src="./assets/images/icon-design.svg
          "
              alt="design icon"
              width="40"
            /> */}
                  </div>
                  <div className="service-content-box">
                    <h4 className="h4 service-item-title">Web Design</h4>
                    <p className="service-item-text">
                      The most modern and high-quality design made at a
                      professional leve
                    </p>
                  </div>
                </li>
                <li className="service-item">
                  <div className="service-icon-box">
                    {/* <img
              src="./assets/images/icon-app.svg"
              alt="mobile app icon"
              width="40"
            /> */}
                  </div>
                  <div className="service-content-box">
                    <h4 className="h4 service-item-title">Mobile apps</h4>
                    <p className="service-item-text">
                      Professional development of applications for iOS and
                      Android.
                    </p>
                  </div>
                </li>
                <li className="service-item">
                  <div className="service-icon-box">
                    {/* <img
              src="./assets/images/icon-photo.svg"
              alt="camera icon"
              width="40"
            /> */}
                  </div>
                  <div className="service-content-box">
                    <h4 className="h4 service-item-title">Photography</h4>
                    <p className="service-item-text">
                      I make high-quality photos of any category at a
                      professional level.
                    </p>
                  </div>
                </li>
              </ul>
            </section>
          </article>
          <article className="resume" data-page="resume">
            <header>
              <h2 className="h2 article-title">Resume</h2>
            </header>
            <section className="timeline">
              <div className="title-wrapper">
                <div className="icon-box">
                  <ion-icon name="book-outline" />
                </div>
                <h3 className="h3">Education</h3>
              </div>
              <ol className="timeline-list">
                <li className="timeline-item">
                  <h4 className="h4 timeline-item-title">
                    JK Lakshmipat Univeraity
                  </h4>
                  <span>2019 — 2023</span>
                  <p className="timeline-text">B.Tech Computer Science</p>
                </li>
              </ol>
            </section>
            <section className="timeline">
              <div className="title-wrapper">
                <div className="icon-box">
                  <ion-icon name="book-outline" />
                </div>
                <h3 className="h3">Experience</h3>
              </div>
              <ol className="timeline-list">
                {/* <li class="timeline-item">
          <h4 class="h4 timeline-item-title">CTO</h4>

          <h5>BrickByBit</h5>
          <span>June, 2023 - Present</span>

          <p class="timeline-text">Web Developmnent Company</p>
        </li> */}
                <li className="timeline-item">
                  <h4 className="h4 timeline-item-title">Frontend Developer</h4>
                  <h5>Doorpix</h5>
                  <span>Jan, 2023 - Present</span>
                  <p className="timeline-text">
                    Develop web applications based on HTML , CSS , JS , React JS
                  </p>
                </li>
                <li className="timeline-item">
                  <h4 className="h4 timeline-item-title">
                    Information Security Analyst Intern
                  </h4>
                  <h5>Cronytechnovest</h5>
                  <span>July, 2021 — September, 2021 (3 months)</span>
                  <p className="timeline-text">
                    Vulnerability Assessment and Penetration Testing(VAPT){" "}
                    <br />
                    Network penetration testing <br />
                    Mobile penetration testing
                    <br />
                  </p>
                </li>
              </ol>
            </section>
          </article>
          <article className="portfolio" data-page="portfolio">
            <headata-filteder>
              <h2 className="h2 article-title">Portfolio</h2>
            </headata-filteder>
            <section className="projects">
              <div className="filter-select-box">
                <button className="filter-select" data-select="" />
              </div>
              <div className="project-list">
                <a href="https://discover-jodhpur.netlify.app" target="_blank">
                  <div className="project-cover">
                    <img
                      src="./assets/images/discover-jodhpur-cover.png"
                      alt="discover-jodhpur"
                      loading="lazy"
                    />
                    <h4>Discover Jodhpur</h4>
                  </div>
                </a>
                <a href="https://excrusion.netlify.app" target="_blank">
                  <div className="project-cover">
                    <img
                      src="./assets/images/excrusion-cover.png"
                      alt="Excrusion"
                      loading="lazy"
                    />
                    <h4>Excrusion</h4>
                  </div>
                </a>
                <a href="https://healthy-omni-food.netlify.app" target="_blank">
                  <div className="project-cover">
                    <img
                      src="./assets/images/healthy-omni-food.png"
                      alt="Omni Food"
                      loading="lazy"
                    />
                    <h4>Omni Food</h4>
                  </div>
                </a>
                <a
                  href="https://yoga-studio-website.netlify.app"
                  target="_blank"
                >
                  <div className="project-cover">
                    <img
                      src="./assets/images/yoga-studio.png"
                      alt="Yoga Studio"
                      loading="lazy"
                    />
                    <h4>Yoga Studio</h4>
                  </div>
                </a>
              </div>
            </section>
          </article>
          <article className="blog" data-page="blog">
            <header>
              <h2 className="h2 article-title">Blog</h2>
            </header>
            <section className="blog-posts">
              <ul className="blog-posts-list">
                <li className="blog-post-item">
                  <a
                    href="https://medium.com/@aayushmehta5225/how-to-become-productive-as-a-developer-2a4b2c3d0758"
                    target="_blank"
                  >
                    {/* <figure class="blog-banner-box">
              <img
                src="./assets/images/blog-6.jpg"
                alt="Design digest #79"
                loading="lazy"
              />
            </figure> */}
                    <div className="blog-content">
                      <div className="blog-meta">
                        <p className="blog-category">Web Development</p>
                        <span className="dot" />
                        <time dateTime="2022-02-23">April 05, 2023</time>
                      </div>
                      <h4 className="h4 blog-item-title">
                        How to become productive as a developer
                      </h4>
                      {/* <p class="blog-text">
                How to become productive as a developer
              </p> */}
                    </div>
                  </a>
                </li>
                <li className="blog-post-item">
                  <a
                    href="https://medium.com/@aayushmehta5225/understanding-box-sizing-and-border-box-2407b8415e06"
                    target="_blank"
                  >
                    {/* <figure class="blog-banner-box">
            <img src="#" alt="#" loading="lazy" />
            </figure> */}
                    <div className="blog-content">
                      <div className="blog-meta">
                        <p className="blog-category">Web Development</p>
                        <span className="dot" />
                        <time dateTime="2022-02-23">April 10, 2023</time>
                      </div>
                      <h4 className="h4 blog-item-title">
                        Understanding box-Sizing and border-box
                      </h4>
                      {/* <p class="blog-text">
                Understanding box-Sizing and border-box
              </p> */}
                    </div>
                  </a>
                </li>
                <li className="blog-post-item">
                  <a
                    href="https://medium.com/@aayushmehta5225/grid-template-area-6a7b9ec94e8a"
                    target="_blank"
                  >
                    {/* <figure class="blog-banner-box">
              <img src="#" alt="#" loading="lazy" />
            </figure> */}
                    <div className="blog-content">
                      <div className="blog-meta">
                        <p className="blog-category">Web Development</p>
                        <span className="dot" />
                        <time dateTime="2022-02-23">April 11, 2023</time>
                      </div>
                      <h4 className="h4 blog-item-title">
                        Understanding grid-template area
                      </h4>
                      {/* <p class="blog-text">
                Understanding box-Sizing and border-box
              </p> */}
                    </div>
                  </a>
                </li>
              </ul>
            </section>
          </article>
        </div>
      </main>
    </>
  );
}
